Correct libfaust.js + asm.js, add asm.js expanded code test in impulse-tests.

diff --git a/tests/impulse-tests/faust2impulse5ter b/tests/impulse-tests/faust2impulse5ter
--- a/tests/impulse-tests/faust2impulse5ter
+++ b/tests/impulse-tests/faust2impulse5ter
@@ -7,7 +7,6 @@
 #                                                                   #
 #####################################################################
 
-
 #-------------------------------------------------------------------
 # Set Faust include path
 
@@ -19,9 +18,9 @@ elif [ -f /usr/local/share/faust/all.lib ]
     FAUSTLIB=/usr/local/share/faust/
 elif [ -f /usr/share/faust/all.lib ]
     then
-FAUSTLIB=/usr/share/faust/
-    else
-echo "ERROR : $0 cannot find Faust library dir (usually /usr/local/share/faust)"
+    FAUSTLIB=/usr/share/faust/
+else
+    echo "ERROR : $0 cannot find Faust library dir (usually /usr/local/share/faust)"
 fi
 
 #-------------------------------------------------------------------
@@ -77,23 +76,21 @@ done
 for f in $FILES; do
 
     name=$(basename "$f" .dsp)
+    name_exp=$name"_exp"
     dirname=$(dirname "$f");
 
-    # compile Faust to wast
-    faust -double $OPTIONS -lang wast-i  "$f" -o "${f%.dsp}.wast" || exit
-
-    # create the nodejs ready file
-    cd $dirname
-    wasm-as "$name.wast" -o "$name.wasm"
-    sed -e "s/mydsp/"$name"/g" "$name.js"  >> "$name-tmp1.js"
-    sed -e "s/mydsp/"$name"/g" $FAUSTLIB/webaudio/wasm-standalone-node-wrapper-double.js >> "$name-tmp1.js"
-    sed -e "s/DSP/"$name"/g" "$name-tmp1.js"  >> "$name-tmp2.js"
+    # compile Faust to asm.js
+    faust -e "$f"
+    cp $FAUSTLIB/webaudio/asm-node-wrapper-double.js "${f%.dsp}.js"
 
 	# run the binary to generate the impulse response
-    node --expose-wasm $name-tmp2.js || exit
+    cd $dirname
+    sed -e "s/SOURCE_FILE/"$name_exp"/g" "$name.js"  >> "$name-tmp1.js"
+    sed -e "s/DSP_NAME/"$name"/g" "$name-tmp1.js"  >> "$name-tmp2.js"
+    node "$name-tmp2.js" || exit
 
     # cleanup
-    rm $name-tmp1.js $name-tmp2.js $name.js $name.wasm $name.wast
+    rm "$name.js" "$name-tmp1.js" "$name-tmp2.js" "$name_exp.dsp"
 
 done
 
