Correct faust2api, test the script in architecture-tests.

diff --git a/tests/architecture-tests/testsuccess b/tests/architecture-tests/testsuccess
--- a/tests/architecture-tests/testsuccess
+++ b/tests/architecture-tests/testsuccess
@@ -58,6 +58,9 @@ if [ "$1" = "osx" ]; then
 
     (faust2api -ios -midi good.dsp &> LOG)&&(echo "OK: faust2api -ios -midi succeeded !")||(echo "ERROR: faust2api -ios -midi failed")
 
+    (faust2api -ios -midi -poly good.dsp &> LOG)&&(echo "OK: faust2api -ios -midi -poly succeeded !")||(echo "ERROR: faust2api -ios -midi -poly failed")
+
+    (faust2api -ios -poly -effect good.dsp -midi good.dsp &> LOG)&&(echo "OK: faust2api -ios -poly -effect good.dsp -midi succeeded !")||(echo "ERROR: faust2api -ios -poly -effect good.dsp -midi failed")
 
 elif [ "$1" = "linux" ]; then
 	echo
@@ -86,6 +89,10 @@ elif [ "$1" = "linux" ]; then
     (faust2api -android good.dsp &> LOG)&&(echo "OK: faust2api -android succeeded !")||(echo "ERROR: faust2api -android failed")
 
     (faust2api -android -midi good.dsp &> LOG)&&(echo "OK: faust2api -android -midi succeeded !")||(echo "ERROR: faust2api -android -midi failed")
+
+    (faust2api -android -midi -poly good.dsp &> LOG)&&(echo "OK: faust2api -android -midi -poly succeeded !")||(echo "ERROR: faust2api -android -midi -poly failed")
+
+    (faust2api -android -poly -effect good.dsp -midi good.dsp &> LOG)&&(echo "OK: faust2api -android -poly -effect good.dsp -midi succeeded !")||(echo "ERROR: faust2api -android -poly -effect good.dsp -midi failed")
 
 else
 	echo
