In faust2xx scripts, replace -poly2 with an explicit -effect foo.dsp parameter.

diff --git a/tests/architecture-tests/testsuccess b/tests/architecture-tests/testsuccess
--- a/tests/architecture-tests/testsuccess
+++ b/tests/architecture-tests/testsuccess
@@ -7,6 +7,7 @@ OSX="faust2au faust2caqt faust2csound faust2faustvst faust2jaqt faust2max6 faust
 OSXMIDI="faust2caqt faust2jaqt faust2max6 faust2msp faust2ios"
 OSXPOLY="faust2caqt faust2jaqt faust2max6 faust2msp faust2ios"
 OSXPOLYMIDI="faust2caqt faust2jaqt faust2max6 faust2msp faust2ios"
+OSXPOLY2MIDI="faust2caqt faust2ios"
 OSXOSCHTTPD="faust2caqt faust2jaqt"
 
 LINUX="faust2alqt faust2alsa faust2alsaconsole faust2android faust2asmjs faust2bela   faust2csound faust2dssi faust2eps faust2faustvst faust2firefox faust2graph faust2graphviewer  faust2jack faust2jackconsole faust2jackinternal faust2jackserver faust2jaqt faust2ladspa faust2lv2 faust2mathdoc  faust2md  faust2netjackconsole faust2netjackqt faust2octave faust2owl faust2paqt faust2pdf faust2plot faust2png faust2puredata faust2raqt faust2ros faust2rosgtk faust2rpialsaconsole faust2rpinetjackconsole faust2sig faust2sigviewer faust2supercollider faust2svg faust2w32max6 faust2w32msp faust2w32puredata faust2w32vst faust2webaudioasm"
@@ -43,6 +44,10 @@ if [ "$1" = "osx" ]; then
 
     for scriptname in $OSXPOLYMIDI; do
         ($scriptname -poly -midi good.dsp &> LOG)&&(echo "OK: $scriptname -poly -midi succeeded !")||(echo "ERROR: $scriptname -poly -midi failed")
+    done
+
+    for scriptname in $OSXPOLY2MIDI; do
+        ($scriptname -poly -effect good.dsp -midi good.dsp &> LOG)&&(echo "OK: $scriptname -poly -effect good.dsp -midi succeeded !")||(echo "ERROR: $scriptname -poly -effect good.dsp -midi failed")
     done
 
     for scriptname in $OSXOSCHTTPD; do
