architecture-tests: wrapper functions to run a test and print its error

diff --git a/tests/architecture-tests/testsuccess b/tests/architecture-tests/testsuccess
--- a/tests/architecture-tests/testsuccess
+++ b/tests/architecture-tests/testsuccess
@@ -38,6 +38,37 @@ notinlist() {
     done
     return 0
 }
+runtest() {
+    # usage: runtest <logfile> <cmd> <arg1> ...
+    local logfile=$1
+    shift
+    ("$@" >"${logfile}" 2>&1) && echo "OK: '$@' succeeded!" || echo "ERROR: '$@' failed"
+    rm -rf good good-faustnode
+}
+runtestfail() {
+    # usage: runtestfail <logfile> <cmd> <arg1> ...
+    local logfile=$1
+    shift
+    ("$@" >"${logfile}" 2>&1) && echo "ERROR: '$@' shouldn't have succeeded!" || echo "OK: '$@' correctly failed"
+    rm -rf good good-faustnode
+}
+runtestref() {
+    # usage: runtestref <logfile> <name> <refbasename> <cmd> <arg1>...
+    local logfile=$1
+    local name=$2
+    local referencefile="${3}_ref.txt"
+    local resultfile="${3}.txt"
+    shift 3
+
+    if ("$@" >"${logfile}" 2>&1); then
+        "./${name}" > "${resultfile}"
+        diff "${resultfile}" "${referencefile}" && echo "OK: '$@' succeeded!" || echo "ERROR: '$@' failed (mismatched output)"
+    else
+        echo "ERROR: '$@' failed"
+    fi
+    rm -f "${resultfile}"
+    rm -rf "${name}"
+}
 
 echo "------------------------"
 echo Run tests for $system
@@ -56,128 +87,86 @@ if [ "$system" = "Darwin" ]; then
     echo "Test -osc -httpd $OSXOSCHTTPD"
     echo "Test -preset auto $OSXPRESET"
 
-    faust2dummy good.dsp > /dev/null
-    ./good > good.txt
-    diff good.txt good_ref.txt && echo "OK: faust2dummy good.dsp succeeded !" || echo "ERROR: faust2dummy good.dsp failed"
-
-    faust2dummy -midi good.dsp > /dev/null
-    ./good > good_midi.txt
-    diff good_midi.txt good_midi_ref.txt && echo "OK: faust2dummy -midi good.dsp succeeded !" || echo "ERROR: faust2dummy -midi good.dsp failed"
-
-    faust2dummy -midi -nvoices 2 organ.dsp > /dev/null
-    ./organ > organ_2voices.txt
-    diff organ_2voices.txt organ_2voices_ref.txt && echo "OK: faust2dummy -midi -nvoices 2 organ.dsp succeeded !" || echo "ERROR: faust2dummy -midi -nvoices 2 organ.dsp failed"
-
-    faust2dummy -midi organ.dsp > /dev/null
-    ./organ > organ_8voices.txt
-    diff organ_8voices.txt organ_8voices_ref.txt && echo "OK: faust2dummy -midi organ.dsp succeeded !" || echo "ERROR: faust2dummy -midi organ.dsp failed"
-
-    faust2dummymem waveform4.dsp > /dev/null
-    ./waveform4 > waveform4.txt
-    diff waveform4.txt waveform4_ref.txt && echo "OK: faust2dummymem waveform4.dsp succeeded !" || echo "ERROR: faust2dummymem waveform4.dsp failed"
+    runtestref LOG good good faust2dummy good.dsp
+    runtestref LOG good_midi good_midi faust2dummy -midi good.dsp
+    runtestref LOG organ organ_2voices faust2dummy -midi -nvoices 2 organ.dsp
+    runtestref LOG organ organ_8voices faust2dummy -midi organ.dsp > /dev/null
+    runtestref LOG waveform4 waveform4 faust2dummymem waveform4.dsp
 
     for scriptname in $OSX; do
-        ($scriptname good.dsp >LOG 2>&1) && (echo "OK: $scriptname succeeded !")||(echo "ERROR: $scriptname failed")
-        rm -rf good
+        runtest LOG "${scriptname}" good.dsp
     done
 
     for scriptname in $OSXMIDI; do
-        ($scriptname -midi good.dsp >LOG 2>&1) && (echo "OK: $scriptname -midi succeeded !")||(echo "ERROR: $scriptname -midi failed")
-        rm -rf good
+        runtest LOG "${scriptname}" -midi good.dsp
     done
 
     for scriptname in $OSXPOLY; do
-        ($scriptname -nvoices 8 good.dsp >LOG 2>&1) && (echo "OK: $scriptname -nvoices 8 succeeded !")||(echo "ERROR: $scriptname -nvoices 8 failed")
-        rm -rf good
+        runtest LOG "${scriptname}" -nvoices 8 good.dsp
     done
 
     for scriptname in $OSXPOLYMIDI; do
-        ($scriptname -nvoices 8 -midi good.dsp >LOG 2>&1) && (echo "OK: $scriptname -nvoices 8 -midi succeeded !")||(echo "ERROR: $scriptname -nvoices 8 -midi failed")
-        rm -rf good
+        runtest LOG "${scriptname}" -nvoices 8 -midi good.dsp
     done
 
     for scriptname in $OSXPOLY2MIDI; do
-        ($scriptname -nvoices 8 -effect good.dsp -midi good.dsp >LOG 2>&1) && (echo "OK: $scriptname -nvoices 8 -effect good.dsp -midi succeeded !")||(echo "ERROR: $scriptname -nvoices 8 -effect good.dsp -midi failed")
-        rm -rf good
+        runtest LOG "${scriptname}" -nvoices 8 -effect good.dsp -midi good.dsp
     done
 
     for scriptname in $OSXSOUND; do
-        ($scriptname -soundfile -lang ocpp sound.dsp >LOG 2>&1) && (echo "OK: $scriptname -soundfile -lang ocpp succeeded !")||(echo "ERROR: $scriptname -soundfile -lang ocpp failed")
-        rm -rf good
+        runtest LOG "${scriptname}" -soundfile -lang ocpp sound.dsp
     done
 
     # Remove sound folder
     rm -rf sound
 
     for scriptname in $OSXSOUND; do
-        ($scriptname -soundfile sound.dsp >LOG 2>&1) && (echo "OK: $scriptname -soundfile succeeded !")||(echo "ERROR: $scriptname -soundfile failed")
-        rm -rf good
+        runtest LOG "${scriptname}" -soundfile sound.dsp
     done
 
     # Remove sound folder
     rm -rf sound
 
     for scriptname in $OSXSOUNDSR; do
-        ($scriptname -soundfile -resample sound.dsp >LOG 2>&1) && (echo "OK: $scriptname -soundfile -resample succeeded !")||(echo "ERROR: $scriptname -soundfile -resample failed")
-        rm -rf good
+        runtest LOG "${scriptname}" -soundfile -resample sound.dsp
     done
 
-    (faust2juce -soundfile -standalone sound.dsp >LOG 2>&1) && (echo "OK: faust2juce -soundfile -standalone succeeded !")||(echo "ERROR: faust2juce -soundfile -standalone failed")
-    rm -rf good
+    runtest LOG faust2juce -soundfile -standalone sound.dsp
 
     for scriptname in $OSXHTTPD; do
-        ($scriptname -httpd good.dsp >LOG 2>&1) && (echo "OK: $scriptname -httpd succeeded !")||(echo "ERROR: $scriptname -httpd failed")
-        rm -rf good
+        runtest LOG "${scriptname}" -httpd good.dsp
     done
 
     for scriptname in $OSXOSC; do
-        ($scriptname -osc good.dsp >LOG 2>&1) && (echo "OK: $scriptname -osc succeeded !")||(echo "ERROR: $scriptname -osc failed")
-        rm -rf good
+        runtest LOG "${scriptname}" -osc good.dsp
     done
 
     for scriptname in $OSXOSCHTTPD; do
-        ($scriptname -osc -httpd good.dsp >LOG 2>&1) && (echo "OK: $scriptname -osc -httpd succeeded !")||(echo "ERROR: $scriptname -osc -httpd failed")
-        rm -rf good
+        runtest LOG "${scriptname}" -osc -httpd good.dsp
     done
 
     for scriptname in $OSXPRESET; do
-        ($scriptname -preset auto good.dsp >LOG 2>&1) && (echo "OK: $scriptname -preset auto succeeded !")||(echo "ERROR: $scriptname -preset auto failed")
-        rm -rf good
+        runtest LOG "${scriptname}" -preset auto good.dsp
     done
 
     (faust2api -jack good.dsp >LOG 2>&1 && unzip dsp-faust.zip && cd dsp-faust && c++ -std=c++11 DspFaust.cpp -DBUILD -ljack -o DspFaust) && (echo "OK: faust2api -jack succeeded !")||(echo "ERROR: faust2api -jack failed")
 
-    (faust2api -jack -midi -nvoices 8 good.dsp >LOG 2>&1) && (echo "OK: faust2api -jack -midi -nvoices 8 succeeded !")||(echo "ERROR: faust2api -jack -midi -nvoices 8 failed")
+    runtest LOG faust2api -jack -midi -nvoices 8 good.dsp
+    runtest LOG faust2api -jack -nvoices 8 -effect effect.dsp -midi good.dsp
+    runtest LOG faust2api -jack -soundfile -lang ocpp sound.dsp
 
-    (faust2api -jack -nvoices 8 -effect effect.dsp -midi good.dsp >LOG 2>&1) && (echo "OK: faust2api -jack -nvoices 8 -effect effect.dsp -midi succeeded !")||(echo "ERROR: faust2api -jack -nvoices 8 -effect effect.dsp -midi failed")
+    runtest LOG faust2nodejs -coreaudio good.dsp
+    runtest LOG faust2nodejs -coreaudio -midi good.dsp
+    runtest LOG faust2nodejs -coreaudio -midi -nvoices 8 good.dsp
+    runtest LOG faust2nodejs -coreaudio -nvoices 8 -effect effect.dsp -midi good.dsp
 
-    (faust2api -jack -soundfile -lang ocpp sound.dsp >LOG 2>&1) && (echo "OK: faust2api -jack -soundfile -lang ocpp succeeded !")||(echo "ERROR: faust2api -jack -soundfile -lang ocpp failed")
-
-    (faust2nodejs -coreaudio good.dsp >LOG 2>&1) && (echo "OK: faust2nodejs -coreaudio succeeded !")||(echo "ERROR: faust2nodejs -coreaudio failed")
-    rm -rf good-faustnode
-
-    (faust2nodejs -coreaudio -midi good.dsp >LOG 2>&1) && (echo "OK: faust2nodejs -coreaudio -midi succeeded !")||(echo "ERROR: faust2nodejs -coreaudio -midi failed")
-    rm -rf good-faustnode
-
-    (faust2nodejs -coreaudio -midi -nvoices 8 good.dsp >LOG 2>&1) && (echo "OK: faust2nodejs -coreaudio -midi -nvoices 8 succeeded !")||(echo "ERROR: faust2nodejs -coreaudio -midi -nvoices 8 failed")
-    rm -rf good-faustnode
-
-    (faust2nodejs -coreaudio -nvoices 8 -effect effect.dsp -midi good.dsp >LOG 2>&1) && (echo "OK: faust2nodejs -coreaudio -nvoices 8 -effect effect.dsp -midi succeeded !")||(echo "ERROR: faust2nodejs -coreaudio -nvoices 8 -effect effect.dsp -midi failed")
-    rm -rf good-faustnode
-
-    (faust2smartkeyb -android good.dsp >LOG 2>&1) && (echo "OK: faust2smartkeyb -android succeeded !")||(echo "ERROR: faust2smartkeyb -android failed")
-
-    (faust2smartkeyb -android -nvoices 8 good.dsp >LOG 2>&1) && (echo "OK: faust2smartkeyb -android -midi -nvoices 8 succeeded !")||(echo "ERROR: faust2smartkeyb -android -midi -nvoices 8 failed")
-
-    (faust2smartkeyb -android -effect effect.dsp -nvoices 8 good.dsp >LOG 2>&1) && (echo "OK: faust2smartkeyb -android -effect effect.dsp -nvoices 8 succeeded !")||(echo "ERROR: faust2smartkeyb -android -effect effect.dsp -nvoices 8 failed")
-
-    (faust2smartkeyb -ios good.dsp >LOG 2>&1) && (echo "OK: faust2smartkeyb -ios succeeded !")||(echo "ERROR: faust2smartkeyb -ios failed")
-
-    (faust2smartkeyb -ios -osc good.dsp >LOG 2>&1) && (echo "OK: faust2smartkeyb -ios -osc succeeded !")||(echo "ERROR: faust2smartkeyb -ios -osc failed")
-
-    (faust2smartkeyb -ios -osc -nvoices 8 good.dsp >LOG 2>&1) && (echo "OK: faust2smartkeyb -ios -osc -nvoices 8 succeeded !")||(echo "ERROR: faust2smartkeyb -ios -osc -nvoices 8 failed")
-
-    (faust2smartkeyb -ios -effect effect.dsp -nvoices 8 good.dsp >LOG 2>&1) && (echo "OK: faust2smartkeyb -ios -effect effect.dsp -nvoices 8 succeeded !")||(echo "ERROR: faust2smartkeyb -ios -effect effect.dsp -nvoices 8 failed")
+    runtest LOG faust2smartkeyb -android good.dsp
+    runtest LOG faust2smartkeyb -android -nvoices 8 good.dsp
+    runtest LOG faust2smartkeyb -android -effect effect.dsp -nvoices 8 good.dsp
+    runtest LOG faust2smartkeyb -ios good.dsp
+    runtest LOG faust2smartkeyb -ios -osc good.dsp
+    runtest LOG faust2smartkeyb -ios -osc -nvoices 8 good.dsp
+    runtest LOG faust2smartkeyb -ios -effect effect.dsp -nvoices 8 good.dsp
 
     # Test of -exp10
     (faust2jack -exp10 exp10.dsp) &&(echo "OK: faust2jack -exp10 succeeded !")||(echo "ERROR: faust2jack -exp10 failed")
@@ -191,57 +180,38 @@ elif [ "$system" = "Linux" ]; then
     echo "Test -nvoices 8 -midi $LINUXPOLYMIDI"
     echo "Test -osc -httpd $LINUXOSCHTTPD"
 
-    faust2dummy good.dsp > /dev/null
-    ./good > good.txt
-    diff good.txt good_ref.txt && echo "OK: faust2dummy good.dsp succeeded !" || echo "ERROR: faust2dummy good.dsp failed"
-
-    faust2dummy -midi good.dsp > /dev/null
-    ./good > good.txt
-    diff good.txt good_ref.txt && echo "OK: faust2dummy -midi good.dsp succeeded !" || echo "ERROR: faust2dummy -midi good.dsp failed"
-
-    faust2dummy -midi -nvoices 2 organ.dsp > /dev/null
-    ./organ > organ_2voices.txt
-    diff organ_2voices.txt organ_2voices_ref.txt && echo "OK: faust2dummy -midi -nvoices 2 organ.dsp succeeded !" || echo "ERROR: faust2dummy -midi -nvoices 2 organ.dsp failed"
-
-    faust2dummy -midi organ.dsp > /dev/null
-    ./organ > organ_8voices.txt
-    diff organ_8voices.txt organ_8voices_ref.txt && echo "OK: faust2dummy -midi organ.dsp succeeded !" || echo "ERROR: faust2dummy -midi organ.dsp failed"
-
-    faust2dummymem waveform4.dsp > /dev/null
-    ./waveform4 > waveform4.txt
-    diff waveform4.txt waveform4_ref.txt && echo "OK: faust2dummymem waveform4.dsp succeeded !" || echo "ERROR: faust2dummy waveform4.dsp failed"
+    runtestref LOG good good faust2dummy good.dsp
+    runtestref LOG good good faust2dummy -midi good.dsp
+    runtestref LOG organ organ_2voices faust2dummy -midi -nvoices 2 organ.dsp
+    runtestref LOG organ organ_8voices faust2dummy -midi organ.dsp
+    runtestref LOG waveform4 waveform4 faust2dummymem waveform4.dsp
 
     for scriptname in $LINUX; do
-        ($scriptname good.dsp >LOG 2>&1) && (echo "OK: $scriptname succeeded !")||(echo "ERROR: $scriptname failed")
+        runtest LOG "${scriptname}" good.dsp
     done
 
     for scriptname in $LINUXMIDI; do
-        ($scriptname -midi good.dsp >LOG 2>&1) && (echo "OK: $scriptname -midi succeeded !")||(echo "ERROR: $scriptname -midi failed")
+        runtest LOG "${scriptname}" -midi good.dsp
     done
 
     for scriptname in $LINUXPOLY; do
-        ($scriptname -nvoices 8 good.dsp >LOG 2>&1) && (echo "OK: $scriptname -nvoices 8 succeeded !")||(echo "ERROR: $scriptname -nvoices 8 failed")
-        rm -rf good
+        runtest LOG "${scriptname}" -nvoices 8 good.dsp
     done
 
     for scriptname in $LINUXPOLYMIDI; do
-        ($scriptname -nvoices 8 -midi good.dsp >LOG 2>&1) && (echo "OK: $scriptname -nvoices 8 -midi succeeded !")||(echo "ERROR: $scriptname -nvoices 8 -midi failed")
-        rm -rf good
+        runtest LOG "${scriptname}" -nvoices 8 -midi good.dsp
     done
 
     for scriptname in $LINUXOSCHTTPD; do
-        ($scriptname -osc -httpd good.dsp >LOG 2>&1) && (echo "OK: $scriptname -osc -httpd succeeded !")||(echo "ERROR: $scriptname -osc -httpd failed")
+        runtest LOG "${scriptname}" -osc -httpd good.dsp
     done
 
     (faust2api -jack good.dsp >LOG 2>&1 && unzip dsp-faust.zip && cd dsp-faust && c++ -std=c++11 DspFaust.cpp -DBUILD -ljack -o DspFaust) && (echo "OK: faust2api -jack succeeded !")||(echo "ERROR: faust2api -jack failed")
 
-    (faust2api -android good.dsp >LOG 2>&1) && (echo "OK: faust2api -android succeeded !")||(echo "ERROR: faust2api -android failed")
-
-    (faust2api -android -midi good.dsp >LOG 2>&1) && (echo "OK: faust2api -android -midi succeeded !")||(echo "ERROR: faust2api -android -midi failed")
-
-    (faust2api -android -midi -nvoices 8 good.dsp >LOG 2>&1) && (echo "OK: faust2api -android -midi -nvoices 8 succeeded !")||(echo "ERROR: faust2api -android -midi -nvoices 8 failed")
-
-    (faust2api -android -nvoices 8 -effect effect.dsp -midi good.dsp >LOG 2>&1) && (echo "OK: faust2api -android -nvoices 8 -effect effect.dsp -midi succeeded !")||(echo "ERROR: faust2api -android -nvoices 8 -effect effect.dsp -midi failed")
+    runtest LOG faust2api -android good.dsp
+    runtest LOG faust2api -android -midi good.dsp
+    runtest LOG faust2api -android -midi -nvoices 8 good.dsp
+    runtest LOG faust2api -android -nvoices 8 -effect effect.dsp -midi good.dsp
 
 elif [ "$system" = "MINGW" ]; then
     echo "not yet implemented"
@@ -251,9 +221,9 @@ else
     echo "Test all Faust2xxx to work"
     echo
     for S in ../../tools/faust2appls/faust2*; do
-        scriptname=`basename $S .in`
+        scriptname=$(basename $S .in)
         if notinlist  $S "$XLIST1"; then
-            ($scriptname good.dsp >LOG 2>&1) && (echo "OK: $scriptname succeeded !")||(echo "ERROR: $scriptname failed")
+            runtest LOG "${scriptname}" good.dsp
         fi
     done
 fi
