faust2api added in architecture-tests.

diff --git a/tests/architecture-tests/testsuccess b/tests/architecture-tests/testsuccess
--- a/tests/architecture-tests/testsuccess
+++ b/tests/architecture-tests/testsuccess
@@ -49,6 +49,11 @@ if [ "$1" = "osx" ]; then
         ($scriptname -osc -httpd good.dsp &> LOG)&&(echo "OK: $scriptname -osc -httpd succeeded !")||(echo "ERROR: $scriptname -osc -httpd failed")
     done
 
+    (faust2api -ios good.dsp &> LOG)&&(echo "OK: faust2api -ios succeeded !")||(echo "ERROR: faust2api -ios failed")
+
+    (faust2api -ios -midi good.dsp &> LOG)&&(echo "OK: faust2api -ios -midi succeeded !")||(echo "ERROR: faust2api -ios -midi failed")
+
+
 elif [ "$1" = "linux" ]; then
 	echo
 	echo "Test $LINUX"
@@ -72,6 +77,10 @@ elif [ "$1" = "linux" ]; then
     for scriptname in $LINUXOSCHTTPD; do
         ($scriptname -osc -httpd good.dsp &> LOG)&&(echo "OK: $scriptname -osc -httpd succeeded !")||(echo "ERROR: $scriptname -osc -httpd failed")
     done
+
+    (faust2api -android good.dsp &> LOG)&&(echo "OK: faust2api -android succeeded !")||(echo "ERROR: faust2api -android failed")
+
+    (faust2api -android -midi good.dsp &> LOG)&&(echo "OK: faust2api -android -midi succeeded !")||(echo "ERROR: faust2api -android -midi failed")
 
 else
 	echo
