ros tests removed, smartkeyb and unity added.

diff --git a/tests/architecture-tests/testserver b/tests/architecture-tests/testserver
--- a/tests/architecture-tests/testserver
+++ b/tests/architecture-tests/testserver
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-LINUX="faust2alqt faust2alsa faust2alsaconsole faust2android faust2asmjs faust2bela faust2csound faust2dssi faust2faustvst faust2graph faust2jack faust2jackconsole faust2jackserver faust2jaqt faust2ladspa faust2lv2 faust2mathdoc faust2netjackconsole faust2netjackqt faust2owl faust2paqt faust2pdf faust2plot faust2png faust2puredata faust2raqt faust2ros faust2rosgtk faust2rpialsaconsole faust2rpinetjackconsole faust2sig faust2supercollider faust2svg faust2w32max6 faust2w32msp faust2w32puredata faust2w32vst faust2webaudioasm faust2netjackconsole"
+LINUX="faust2alqt faust2alsa faust2alsaconsole faust2android faust2asmjs faust2bela faust2csound faust2dssi faust2faustvst faust2graph faust2jack faust2jackconsole faust2jackserver faust2jaqt faust2ladspa faust2lv2 faust2mathdoc faust2netjackconsole faust2netjackqt faust2owl faust2paqt faust2pdf faust2plot faust2png faust2puredata faust2sig faust2supercollider faust2svg faust2w32max6 faust2w32msp faust2w32puredata faust2w32vst faust2webaudioasm faust2netjackconsole"
 LINUXMIDI="faust2jaqt"
 LINUXPOLY="faust2jaqt faust2juce"
 LINUXPOLYMIDI="faust2jaqt faust2juce"
@@ -33,6 +33,10 @@ done
 for scriptname in $LINUXOSCHTTPD; do
     ($scriptname -osc -httpd good.dsp &> LOG)&&(echo "OK: $scriptname -osc -httpd succeeded !")||(echo "ERROR: $scriptname -osc -httpd failed")
 done
+
+(faust2unity -android -linux -w32 -w64 good.dsp &> LOG)&&(echo "OK: faust2smartkeyb -android succeeded !")||(echo "ERROR: faust2smartkeyb -android failed")
+
+(faust2smartkeyb -android good.dsp &> LOG)&&(echo "OK: faust2smartkeyb -android succeeded !")||(echo "ERROR: faust2smartkeyb -android failed")
 
 (faust2api -android good.dsp &> LOG)&&(echo "OK: faust2api -android succeeded !")||(echo "ERROR: faust2api -android failed")
 
