Correct vumeter.dsp and dbmeter.dsp examples to avoid paths with adresses in bargraph. More complete 'faust2api' test.

diff --git a/tests/architecture-tests/testsuccess b/tests/architecture-tests/testsuccess
--- a/tests/architecture-tests/testsuccess
+++ b/tests/architecture-tests/testsuccess
@@ -53,7 +53,7 @@ if [ "$system" = "Darwin" ]; then
     echo "Test -httpd $OSXHTTPD"
     echo "Test -osc $OSXOSC"
     echo "Test -osc -httpd $OSXOSCHTTPD"
-    
+  
     faust2dummy good.dsp > /dev/null
     ./good > good.txt
     diff good.txt good_ref.txt && echo "OK: faust2dummy good.dsp succeeded !" || echo "ERROR: faust2dummy good.dsp failed"
@@ -132,16 +132,14 @@ if [ "$system" = "Darwin" ]; then
     for scriptname in $OSXOSCHTTPD; do
         ($scriptname -osc -httpd good.dsp &> LOG)&&(echo "OK: $scriptname -osc -httpd succeeded !")||(echo "ERROR: $scriptname -osc -httpd failed")
     done
+    
+    (faust2api -jack good.dsp &> LOG && unzip dsp-faust.zip && cd dsp-faust && c++ -std=c++11 DspFaust.cpp -DBUILD -ljack -o DspFaust)&&(echo "OK: faust2api -jack succeeded !")||(echo "ERROR: faust2api -jack failed")
+    
+    (faust2api -jack -midi -nvoices 8 good.dsp &> LOG)&&(echo "OK: faust2api -jack -midi -nvoices 8 succeeded !")||(echo "ERROR: faust2api -jack -midi -nvoices 8 failed")
 
-    (faust2api -ios good.dsp &> LOG)&&(echo "OK: faust2api -ios succeeded !")||(echo "ERROR: faust2api -ios failed")
+    (faust2api -jack -nvoices 8 -effect effect.dsp -midi good.dsp &> LOG)&&(echo "OK: faust2api -jack -nvoices 8 -effect effect.dsp -midi succeeded !")||(echo "ERROR: faust2api -jack -nvoices 8 -effect effect.dsp -midi failed")
 
-    (faust2api -ios -midi good.dsp &> LOG)&&(echo "OK: faust2api -ios -midi succeeded !")||(echo "ERROR: faust2api -ios -midi failed")
-
-    (faust2api -ios -midi -nvoices 8 good.dsp &> LOG)&&(echo "OK: faust2api -ios -midi -nvoices 8 succeeded !")||(echo "ERROR: faust2api -ios -midi -nvoices 8 failed")
-
-    (faust2api -ios -nvoices 8 -effect effect.dsp -midi good.dsp &> LOG)&&(echo "OK: faust2api -ios -nvoices 8 -effect effect.dsp -midi succeeded !")||(echo "ERROR: faust2api -ios -nvoices 8 -effect effect.dsp -midi failed")
-
-	(faust2api -ios -soundfile -lang ocpp sound.dsp &> LOG)&&(echo "OK: faust2api -ios -soundfile -lang ocpp succeeded !")||(echo "ERROR: faust2api -ios -soundfile -lang ocpp failed")
+    (faust2api -jack -soundfile -lang ocpp sound.dsp &> LOG)&&(echo "OK: faust2api -jack -soundfile -lang ocpp succeeded !")||(echo "ERROR: faust2api -jack -soundfile -lang ocpp failed")
 
     (faust2nodejs -coreaudio good.dsp &> LOG)&&(echo "OK: faust2nodejs -coreaudio succeeded !")||(echo "ERROR: faust2nodejs -coreaudio failed")
 
@@ -218,6 +216,8 @@ elif [ "$system" = "Linux" ]; then
     for scriptname in $LINUXOSCHTTPD; do
         ($scriptname -osc -httpd good.dsp &> LOG)&&(echo "OK: $scriptname -osc -httpd succeeded !")||(echo "ERROR: $scriptname -osc -httpd failed")
     done
+
+    (faust2api -jack good.dsp &> LOG && unzip dsp-faust.zip && cd dsp-faust && c++ -std=c++11 DspFaust.cpp -DBUILD -ljack -o DspFaust)&&(echo "OK: faust2api -jack succeeded !")||(echo "ERROR: faust2api -jack failed")
 
     (faust2api -android good.dsp &> LOG)&&(echo "OK: faust2api -android succeeded !")||(echo "ERROR: faust2api -android failed")
 
