Fix faust2jackconsole, cleanup.

diff --git a/tools/faust2appls/faust2jackconsole b/tools/faust2appls/faust2jackconsole
--- a/tools/faust2appls/faust2jackconsole
+++ b/tools/faust2appls/faust2jackconsole
@@ -10,7 +10,27 @@
 . faustpath
 . faustoptflags
 
+#-------------------------------------------------------------------
+# Set Faust include path
+
+if [ -f $FAUST_LIB_PATH/music.lib ]
+then
+    FAUSTLIB=$FAUST_LIB_PATH
+elif [ -f /usr/local/share/faust/music.lib ]
+then
+    FAUSTLIB=/usr/local/share/faust/
+elif [ -f /usr/share/faust/music.lib ]
+then
+    FAUSTLIB=/usr/share/faust/
+else
+    echo "ERROR : $0 cannot find Faust library dir (usually /usr/local/share/faust)"
+fi
+
+CXX=g++
+CXXFLAGS=$MYGCCFLAGS
+
 OSCDEFS=""
+ARCHFILE="jack-console.cpp"
 
 #-------------------------------------------------------------------
 # Analyze command arguments :
@@ -21,8 +41,6 @@ OSCDEFS=""
 
 # PHASE 1 : Look for -icc option to force use of intel icc (actually icpc)
 # without having to configure CXX and CXXFLAGS
-CXX=g++
-CXXFLAGS=$MYGCCFLAGS
 
 for p in $@; do
 	if [ "$p" = -icc ]; then
@@ -73,7 +91,7 @@ done
 for f in $FILES; do
 	
 	# compile faust to c++
-	faust -i -a "$FAUSTLIB/jack-console.cpp" $OPTIONS "$f" -o "$f.cpp" || exit
+	faust -i -a $ARCHFILE $OPTIONS "$f" -o "$f.cpp" || exit
 
 	# compile c++ to binary
 	(
