Fixes and new features
* Potential overwrites of global variables mitigated
* Simplified interface with pedal tools build/install
* Deriving the stratus metadata from the c++ file
* Ability to use faust2stratus for direct c++ compiles (i.e. not just starting from DSP files
* Expanded doc

diff --git a/tools/faust2appls/faust2stratus b/tools/faust2appls/faust2stratus
--- a/tools/faust2appls/faust2stratus
+++ b/tools/faust2appls/faust2stratus
@@ -1,7 +1,8 @@
 #!/bin/bash
 #####################################################################
 #                                                                   #
-#               Compiles Faust programs for the Chaos Stratus pedal #
+#  Compiles Faust programs for the Chaos Stratus pedal with         #
+#  optional CPP compile and pedal install                           #
 #                                                                   #
 #####################################################################
 
@@ -13,8 +14,6 @@ ARCHFILE=${STRATUS_ARCH:-chaos-stratus/stratus.cpp}
 HOSTNAME="$(hostname)"
 CPPCOMPILE=true
 export TMPDIR=$(mktemp -d)
-PEDAL_BUILD="buildOnStratus"
-which docker > /dev/null && PEDAL_BUILD="buildWithDocker"
 
 ##
 ## Install cleanup routine
@@ -42,17 +41,30 @@ _term() {
 #
 echoHelp() 
 {
-    usage faust2stratus "[options] [Faust options] <file.dsp> ..."
+    usage faust2stratus "[options] [Faust options] <file.dsp> ... [<file.cpp> ...]"
     platform "Chaos Audio Stratus pedal"
     echo "Compiles Faust programs for the Chaos Audio Stratus pedal"
-    echo "Can be used build and install multiple different effects in one go"
-    option "-nocppc" "Do not compile the generated CPP source files"
+    echo "  with optional c++ compile for, and effect install to, the pedal"
+    echo
+    echo "Unlike most other "faust2xxx" scripts, this can also be used to compile"
+    echo "  effect c++ code that has been constructed elsewhere, or has been modified "
+    echo "  after being generated by the Faust compiler (e.g. where the algorithm c++ code"
+    echo "  has been 'tweaked' after generation)"
+    echo
+    echo "The script can be used to build and install multiple different effects in one go"
+    echo
+    echo "Running this script with no options except input files will result in effect libraries"
+    echo "  built for the platform upon which the script is executed, not for the pedal"
+    echo
+    echo "Options:"
+    option "-nocppc" "Do not compile the generated c++ source files"
     option "-nodocker" "Do not use docker for pedal builds even if it is available"
-    option "-stratusbuild" "Generates the CPP code locally, then builds the effect library on the Stratus pedal"
-    option "-stratusinstall" "Generates the CPP code locally, then builds and installs the effect library on the Stratus pedal"
+    option "-stratusbuild" "Generates the c++ code locally, then builds the effect library for the Stratus pedal"
+    option "-stratusinstall" "Generates the c++ code locally, then builds and installs the effect library for the Stratus pedal"
+    echo
     option "Faust options"
-    echo   "      the script uses '-i -scn FaustDSP -light -nvi'"
-    echo   "      -O and/or -o can be used, otherwise all output is in the same folder as the corresponding input"
+    echo   "     the script automatically uses '-i -scn FaustDSP -light -nvi'"
+    echo   "     -O and/or -o can be used, otherwise all output is in the same folder as the corresponding input"
     exit
 }
 
@@ -88,7 +100,7 @@ while [[ "$1" ]]; do
     elif [[ "${opt}" =~ ^--?"nocppc"$ ]]; then
         CPPCOMPILE="false"
     elif [[ "${opt}" =~ ^--?"nodocker"$ ]]; then
-        PEDAL_BUILD="buildOnStratus"
+        NO_DOCKER="-nodocker"
     elif [[ "${opt}" =~ ^--?"stratusclass"$ ]]; then
         STRATUSCLASS=${1:-dsp}
         shift
@@ -125,99 +137,50 @@ OUTPUT_FILE=${OUTPUT_FILE:+$(basename ${OUTPUT_FILE})}
 
 for f in ${FILES}; do
 
+    # Some old Macs don't have realpath!
     EFFECT="$([[ ! "${f}" =~ ^/ ]] && echo "${PWD}/")${f}"
 
     EFFECT_OUPUT_DIR=${OUTPUT_DIR:-$(dirname "${EFFECT}")}
 
-    # Derive the various output file names based on -o (first only) or the input file name
+    # Derive the c++ file name based on -o (first only) or the input file name
     EFFECT_FILENAME="${OUTPUT_FILE:-$(basename ${EFFECT})}"
-    OUTPUT_FILE_STEM="${EFFECT_FILENAME%%.*}"
 
     # -o, if presented, is interpreted as the Faust compiler output file name (first only)
-    EFFECT_CPP="${EFFECT_OUPUT_DIR}/${OUTPUT_FILE:-${OUTPUT_FILE_STEM}.cpp}"
-    # The SO file name is based on the output file stem wherever that came from
-    EFFECT_SO="${EFFECT_OUPUT_DIR}/${OUTPUT_FILE_STEM}.so"
+    EFFECT_CPP="${EFFECT_OUPUT_DIR}/${OUTPUT_FILE:-${EFFECT_FILENAME%.*}.cpp}"
 
     # In a multi-file build, the "-o" option can only apply to the first DSP file
     OUTPUT_FILE=""
     
     # compile faust to c++
-    echo "Building effect ${EFFECT}:" >&2
+    echo "Building effect ${EFFECT_CPP} with Faust:"
     echo "  Faust options: -a ${ARCHFILE} ${OPTIONS} ${EFFECT} -o ${EFFECT_CPP}"
 
     faust -a ${ARCHFILE} ${OPTIONS} "${EFFECT}" -o "${EFFECT_CPP}" || exit
 
-    if [[ "${CPPCOMPILE}" == true ]]; then
-        if [[ "${STRATUSINSTALL}" == true ]]; then
-            setIDandVersion "${EFFECT}"
-            if [[ -z "${EFFECT_ID}" ]]; then
-                echo "Unable to find 'stratusId' in the effect metadata - install not possible"
-                STRATUSINSTALL=""
-            fi
-        fi
-
-        #
-        # We are supposed to compile - but what is our context?
-        #
-
-        #
-        # If we are on the Stratus, or we are NOT supposed to build on the stratus, then it's simply a local compile
-        #
-        if [[ "${HOSTNAME}" == "stratus" || "${STRATUSBUILD}" != "true" ]]; then
-            buildLocal "${EFFECT_CPP}" "${EFFECT_SO}" || { echo "Local build failed"; exit 1; }
-            if [[ "${HOSTNAME}" == "stratus" && "${STRATUSINSTALL}" == "true" ]]; then
-                installLocal "${EFFECT_SO}" "${EFFECT_ID}" "${EFFECT_VERSION}" || { echo "Install on stratus failed"; exit 1; }
-            fi
-        else
-            #
-            # If we are not on the Stratus, and we are supposed to at least build on the stratus, then do that
-            #
-            ${PEDAL_BUILD} "${EFFECT_CPP}" "${EFFECT_SO}" || { echo "Build for stratus failed"; exit 1; }
-            if [[ "${STRATUSINSTALL}" == "true" ]]; then
-                installOnStratus "${EFFECT_SO}" "${EFFECT_ID}" "${EFFECT_VERSION}" || { echo "Install on stratus failed"; exit 1; }
-            fi
-        fi
-    else
-        echo "NOT CPP compiling ${EFFECT_CPP} (-nocppc specified)"
-    fi
+    CPPFILES="${EFFECT_CPP} ${CPPFILES}"
 done
 
 #
-# And now the CPP files - i.e. those that were manually massaged!
+# And now the CPP files - generated and specified
 #
-if [[ "${CPPCOMPILE}" == true ]]; then
-    for f in ${CPPFILES}; do
-        EFFECT_CPP=$f
-        if [[ "${STRATUSINSTALL}" == true ]]; then
-            setIDandVersion "${EFFECT}"
-            if [[ -z "${EFFECT_ID}" ]]; then
-                echo "Unable to find 'stratusId' in the effect metadata - install not possible"
-                STRATUSINSTALL=""
-            fi
-        fi
+if [[ "${CPPCOMPILE}" == "true" ]]; then
+    for EFFECT_CPP in ${CPPFILES}; do
+        EFFECT_SO="${EFFECT_CPP%.cpp}.so"
+        setIDandVersion "${EFFECT_CPP}"
 
         #
-        # We are supposed to compile - but what is our context?
+        # If we are building or installing for the Stratus we use pedalBuild, otherwise we use buildLocal
         #
-
-        #
-        # If we are on the Stratus, or we are NOT supposed to build on the stratus, then it's simply a local compile
-        #
-        if [[ "${HOSTNAME}" == "stratus" || "${STRATUSBUILD}" != "true" ]]; then
-            buildLocal "${EFFECT_CPP}" "${EFFECT_SO}" || { echo "Local build failed"; exit 1; }
-            if [[ "${HOSTNAME}" == "stratus" && "${STRATUSINSTALL}" == "true" ]]; then
-                installLocal "${EFFECT_SO}" "${EFFECT_ID}" "${EFFECT_VERSION}" || { echo "Install on stratus failed"; exit 1; }
+        if [[ "${STRATUSBUILD}" == "true" ]]; then
+            pedalBuild $NO_DOCKER "${EFFECT_CPP}" "${EFFECT_SO}" || { echo "Pedal build of ${EFFECT_CPP} failed"; exit 1; }
+            if [[ "${STRATUSINSTALL}" == "true" ]]; then
+                [[ -z "${EFFECT_ID}" ]] && { echo "Unable to find 'stratusId' in ${EFFECT_CPP} - install not possible"; continue; }
+                pedalInstall "${EFFECT_SO}" "${EFFECT_ID}" "${EFFECT_VERSION}" || { echo "Pedal install of ${EFFECT_SO} failed"; exit 1; }
             fi
         else
-            #
-            # If we are not on the Stratus, and we are supposed to at least build on the stratus, then do that
-            #
-            ${PEDAL_BUILD} "${EFFECT_CPP}" "${EFFECT_SO}" || { echo "Build for stratus failed"; exit 1; }
-            if [[ "${STRATUSINSTALL}" == "true" ]]; then
-                installOnStratus "${EFFECT_SO}" "${EFFECT_ID}" "${EFFECT_VERSION}" || { echo "Install on stratus failed"; exit 1; }
-            fi
+            buildLocal $NO_DOCKER "${EFFECT_CPP}" "${EFFECT_SO}" || { echo "Local build of ${EFFECT_CPP} failed"; exit 1; }
         fi
     done
 else
-    [[ "$CPPFILES" ]] && echo "NOT CPP compiling ${CPPFILES} (-nocppc specified)"
+    [[ "$CPPFILES" ]] && echo "Not compiling ${CPPFILES} (-nocppc specified)"
 fi
