print variable-name in error message (to make it easier to fix)

diff --git a/tools/faust2appls/faust2w32max6 b/tools/faust2appls/faust2w32max6
--- a/tools/faust2appls/faust2w32max6
+++ b/tools/faust2appls/faust2w32max6
@@ -16,7 +16,7 @@ MAXSDK=/usr/local/include/c74support
 EXT="~.mxe"
 
 if [ -d "${MAXSDK}" ]; then
- echo "Unable to locate Max/Msp SDK: ${MAXSDK}" 1>&2
+ echo "Unable to locate Max/Msp SDK: MAXSDK=${MAXSDK}" 1>&2
  exit 1
 fi
 
diff --git a/tools/faust2appls/faust2w32vst b/tools/faust2appls/faust2w32vst
--- a/tools/faust2appls/faust2w32vst
+++ b/tools/faust2appls/faust2w32vst
@@ -14,7 +14,7 @@
 VST=/usr/local/include/vstsdk2.4
 . faustpath
 if [ -d "${VST}" ]; then
-  echo "unable to locate VST SDK: ${VST}" 1>&2
+  echo "unable to locate VST SDK: VST=${VST}" 1>&2
 fi
 
 # these cpp files have to be compiled too
