Some fixes in faust2unity, cleanup.

diff --git a/tools/faust2appls/faust2androidunity b/tools/faust2appls/faust2androidunity
--- a/tools/faust2appls/faust2androidunity
+++ b/tools/faust2appls/faust2androidunity
@@ -9,14 +9,11 @@
 #                                                                                                           #
 #############################################################################################################
 
-
 #   This script shouldn't be used on its own, use the "faust2unity" script instead
 #   The libraries are firstly wrapped by the unityplugin.cpp architecture file
 #   They have to be used in the Unity environment
 #   The libraries does not work by themselves, they need the FaustPlugin_<dspname>.cs and FaustUtilities_<dspname>.cs files to be functionnal
 #   These files are automatically generated by the "faust2unity" script
-
-
 
 . faustpath
 
@@ -66,7 +63,7 @@ for p in $FILES; do
     fi
 
     # compiles faust to c++
-    faust -i -a unity/unityplugin.cpp $OPTIONS "$SRCDIR/$f" -o "$TMP/$NAME.cpp" || (echo "$f : Faust to C++ compilation failed in faust2androidunity"; exit 1)
+    faust -i -a $FAUSTLIB/unity/unityplugin.cpp $OPTIONS "$SRCDIR/$f" -o "$TMP/$NAME.cpp" || (echo "$f : Faust to C++ compilation failed in faust2androidunity"; exit 1)
 
     # compiles c++ to binary
     cd "$TMP"
@@ -90,5 +87,6 @@ for p in $FILES; do
     rm -rf $TMP
 
     echo "$f : Android armeabi-v7a and x86 compilations completed"
+
 done
 
diff --git a/tools/faust2appls/faust2linuxunity b/tools/faust2appls/faust2linuxunity
--- a/tools/faust2appls/faust2linuxunity
+++ b/tools/faust2appls/faust2linuxunity
@@ -8,13 +8,13 @@
 #                                                                                                           #
 #############################################################################################################
 
-
 #   This script shouldn't be used on its own, use the "faust2unity" script instead
 #   The libraries are firstly wrapped by the unityplugin.cpp architecture file
 #   They have to be used in the Unity environment
 #   The libraries does not work by themselves, they need the FaustPlugin_<dspname>.cs and FaustUtilities_<dspname>.cs files to be functionnal
 #   These files are automatically generated by the "faust2unity" script
 
+. faustpath
 
 #-------------------------------------------------------------------
 # Dispatch command arguments
@@ -37,14 +37,12 @@ for p in $@; do
 	fi
 done
 
-
 #------------------------------------------------------------------------------
 # Compiler g++
 #
 
 CXX="g++"
 (which "$CXX" >/dev/null) || (echo "compiler $CXX not found. See -help for more info"; exit 1)
-
 
 #-------------------------------------------------------------------
 # Compiler settings
@@ -58,7 +56,6 @@ fi
 CXXFLAGS="-O3 -fPIC $MARCH -mfpmath=sse -msse -msse2 -msse3 -ffast-math -ftree-vectorize"
 LIB="-shared"
 EXT=".so"
-
 
 #-------------------------------------------------------------------
 # compile the *.dsp files
@@ -83,7 +80,7 @@ for p in $FILES; do
     fi
 
     # compile faust to c++
-    faust -i -a unity/unityplugin.cpp $OPTIONS "$SRCDIR/$f" -o "$TMP/$NAME.cpp" || (echo "$f : Faust to C++ compilation failed in faust2linuxunity"; exit 1)
+    faust -i -a $FAUSTLIB/unity/unityplugin.cpp $OPTIONS "$SRCDIR/$f" -o "$TMP/$NAME.cpp" || (echo "$f : Faust to C++ compilation failed in faust2linuxunity"; exit 1)
 
     # compile c++ to binary
     (
diff --git a/tools/faust2appls/faust2osxiosunity b/tools/faust2appls/faust2osxiosunity
--- a/tools/faust2appls/faust2osxiosunity
+++ b/tools/faust2appls/faust2osxiosunity
@@ -25,14 +25,14 @@
 #           Info.plist
 #
 
+. faustpath
 
 #------------------------------------------------
-# Compilater settings
+# Compiler settings
 
 CXXFLAGS="-I. -O3 -fPIC -arch i386 -arch x86_64"
 LDFLAGS="-bundle"
 CXX="c++"
-
 
 #------------------------------------------------
 # Generates the info.plist file
@@ -104,7 +104,6 @@ cat > "$2" << DELIM
 DELIM
 }
 
-
 #---------------------------------------
 # Dispatch command arguments
 
@@ -136,7 +135,6 @@ for p in $@; do
 
 done
 
-
 #--------------------------------------
 # Compiles all *.dsp files
 
@@ -146,7 +144,6 @@ for p in $FILES; do
     NAME=${f%.dsp}
     FNAME=FaustPlugin_$NAME
     SRCDIR=$(dirname "$p")
-
 
     if [ "$IOS" = "1" ]; then # iOS part
 
@@ -161,7 +158,7 @@ for p in $FILES; do
         fi
 
         # compiles faust to c++
-        faust -i -a unity/unityplugin.cpp "$SRCDIR/$NAME.dsp" -o $TMP/$NAME.cpp || (echo "$FNAME : Faust to C++ compilation failed in faust2osxiosunity -ios"; exit 1)
+        faust -i -a $FAUSTLIB/unity/unityplugin.cpp "$SRCDIR/$NAME.dsp" -o $TMP/$NAME.cpp || (echo "$FNAME : Faust to C++ compilation failed in faust2osxiosunity -ios"; exit 1)
 
         $CXX $CXXFLAGS -DAPPLE -fembed-bitcode -DPLUGINNAME="libFaustPlugin_$NAME" -std=c++11 -stdlib=libc++ -c -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk $TMP/$NAME.cpp -o $TMP/$NAME.o || (echo "$FNAME : C++ to iOS library compilation failed in faust2osxiosunity -ios"; exit 1)
         libtool $TMP/$NAME.o -o $TMP/libFaustPlugin_$NAME.a
@@ -190,8 +187,8 @@ for p in $FILES; do
             mkdir -p "$FIN"
         fi
 
-        # compile faust to c++
-        faust -i -a unity/unityplugin.cpp "$SRCDIR/$NAME.dsp" -o "$MOS/$NAME.cpp" || (echo "$FNAME : Faust to C++ compilation failed in faust2osxiosunity"; exit 1)
+        # compile Faust DSP to c++
+        faust -i -a $FAUSTLIB/unity/unityplugin.cpp "$SRCDIR/$NAME.dsp" -o "$MOS/$NAME.cpp" || (echo "$FNAME : Faust to C++ compilation failed in faust2osxiosunity"; exit 1)
 
         $CXX $CXXFLAGS $LDFLAGS -DAPPLE -DPLUGINNAME="$NAME" "$MOS/$NAME.cpp" -o "$MOS/lib$FNAME" || (echo "$FNAME : C++ to OSX library compilation failed in faust2osxiosunity"; exit 1)
         rm "$MOS/$NAME.cpp"
