Cleanup faust2xx tools.

diff --git a/tools/faust2appls/faust2bela b/tools/faust2appls/faust2bela
--- a/tools/faust2appls/faust2bela
+++ b/tools/faust2appls/faust2bela
@@ -34,6 +34,7 @@ do
     if [ $p = "-help" ] || [ $p = "-h" ]; then
         usage faust2bela "[options] [Faust options] <file.dsp>"
         platform Bela
+        echo "Compiles Faust programs to the BELA board"
         option
         options -osc -midi -soundfile
         option "-nvoices <num>"
@@ -41,7 +42,7 @@ do
         option -gui "activates a self-hosted GUI interface. Requires to have libmicrohttpd and libHTTPDFaust installed."
         option "-effect <effect.dsp>" "generates a polyphonic DSP connected to a global output effect, ready to be used with MIDI"
         option "-effect auto" "generates a polyphonic DSP connected to a global output effect defined as 'effect' in <file.dsp>, ready to be used with MIDI"
-	    option -tobela "to send C++ file into bela, and to run it."
+        option -tobela "to send C++ file into bela, and to run it."
         exit
     fi
 
@@ -92,23 +93,23 @@ faust $FAUST_ARGS -i -a $ARCHFILE $OPTIONS "$INPUT_FILE" -o "$FAUST_MAIN_OUTPUT"
 
 EFFECT_OUTPUT=$TMP/effect.h
 if [[ "$POLY" == *POLY2* ]]; then
-	if [ $EFFECT = "auto" ]; then
-		# Creer un fichier .dsp simple
-		cat > $TMP/effect.dsp << EndOfCode
-		adapt(1,1) = _;
-		adapt(2,2) = _,_;
-		adapt(1,2) = _ <: _,_;
-		adapt(2,1) = _,_ :> _;
+    if [ $EFFECT = "auto" ]; then
+        # Creer un fichier .dsp simple
+        cat > $TMP/effect.dsp << EndOfCode
+        adapt(1,1) = _;
+        adapt(2,2) = _,_;
+        adapt(1,2) = _ <: _,_;
+        adapt(2,1) = _,_ :> _;
 
-		adaptor(F,G) = adapt(outputs(F),inputs(G));
+        adaptor(F,G) = adapt(outputs(F),inputs(G));
 
-		process = adaptor(library("$INPUT_FILE").process, library("$INPUT_FILE").effect) : library("$INPUT_FILE").effect;
+        process = adaptor(library("$INPUT_FILE").process, library("$INPUT_FILE").effect) : library("$INPUT_FILE").effect;
 EndOfCode
-		faust $FAUST_ARGS -i -cn effect -a minimal-effect.cpp "$TMP/effect.dsp" -o "$EFFECT_OUTPUT"
+        faust $FAUST_ARGS -i -cn effect -a minimal-effect.cpp "$TMP/effect.dsp" -o "$EFFECT_OUTPUT"
 
-	else
-		faust $FAUST_ARGS -i -cn effect -a minimal-effect.cpp "$EFFECT" -o "$EFFECT_OUTPUT"
-	fi
+    else
+        faust $FAUST_ARGS -i -cn effect -a minimal-effect.cpp "$EFFECT" -o "$EFFECT_OUTPUT"
+    fi
 fi
 
 #-------------------------------------------------------------------
@@ -117,24 +118,24 @@ fi
 
 echo '// Options :' > "$PROJECTDIR/tmp.txt"
 if [ $NVOICES -gt 0 ]; then
-	echo '#define NVOICES '$NVOICES >> "$PROJECTDIR/tmp.txt"
+    echo '#define NVOICES '$NVOICES >> "$PROJECTDIR/tmp.txt"
 fi
 
 if [[ "$MIDIDEFS" == *MIDI* ]]; then
-	echo '#define MIDICTRL' >> "$PROJECTDIR/tmp.txt"
+    echo '#define MIDICTRL' >> "$PROJECTDIR/tmp.txt"
 fi
 
 if [[ "$POLY" == *POLY2* ]]; then
-	echo '#define POLY2' >> "$PROJECTDIR/tmp.txt"
+    echo '#define POLY2' >> "$PROJECTDIR/tmp.txt"
 fi
 
 if [[ "$OSCDEFS" == *OSC* ]]; then
-	echo '#define OSCCTRL' >> "$PROJECTDIR/tmp.txt"
+    echo '#define OSCCTRL' >> "$PROJECTDIR/tmp.txt"
 fi
 
 if [[ "$GUIDEFS" == *GUI* ]]; then
-	echo '#define HTTPDGUI' >> "$PROJECTDIR/tmp.txt"
-	BELA_LDLIBS="$BELA_LDLIBS -lHTTPDFaust"
+    echo '#define HTTPDGUI' >> "$PROJECTDIR/tmp.txt"
+    BELA_LDLIBS="$BELA_LDLIBS -lHTTPDFaust"
 fi
 
 if [[ "$SOUNDFILEDEFS" == *SOUNDFILE* ]]; then
@@ -151,9 +152,9 @@ rm -rf "$PROJECTDIR/tmp"
 #-------------------------------------------------------------------
 
 if [[ "$SEND2BELA" == *OK* ]]; then
-	echo "Send to bela"
-	echo $PROJECTDIR
-	
+    echo "Send to bela"
+    echo $PROJECTDIR
+    
 #-------------------------------------------------------------------
 #From build_project.sh :
 #-------------------------------------------------------------------
@@ -164,22 +165,22 @@ BELA_DONT_RUN_FIRST=0
 
 # FUNCTIONS:+++++++++++++++++++++++++++++++
 check_rsync(){
-	if [ -z "`which rsync 2> /dev/null`" ]
-	then
-		return 1
-	else
-		return 0
-	fi
+    if [ -z "`which rsync 2> /dev/null`" ]
+    then
+        return 1
+    else
+        return 0
+    fi
 }
 
 check_board_alive_and_set_date(){
-	printf "Checking the board is up and running at $BBB_ADDRESS..."
-	# Clear the host if it is cached in ~/.ssh/known_hosts.
-	ssh-keygen -R $BBB_HOSTNAME &> /dev/null || true
-	ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 $BBB_ADDRESS "date -s \"`date '+%Y%m%d %T %z'`\" > /dev/null" && printf "done\n" || {
-		printf "\nERROR: the board does not respond at $BBB_ADDRESS, check that the address is correct and the board is connected.\n";
-		exit 1;
-	}
+    printf "Checking the board is up and running at $BBB_ADDRESS..."
+    # Clear the host if it is cached in ~/.ssh/known_hosts.
+    ssh-keygen -R $BBB_HOSTNAME &> /dev/null || true
+    ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 $BBB_ADDRESS "date -s \"`date '+%Y%m%d %T %z'`\" > /dev/null" && printf "done\n" || {
+        printf "\nERROR: the board does not respond at $BBB_ADDRESS, check that the address is correct and the board is connected.\n";
+        exit 1;
+    }
 }
 
 #+++++++++++++++++++++++++++++++++++++++++++
@@ -190,8 +191,8 @@ EXTENSIONS_TO_FIND='\.cpp\|\.c\|\.S\|\.pd\|\.scd'
 FOUND_FILES=$($FIND_STRING 2>/dev/null | grep "$EXTENSIONS_TO_FIND")
 if [ -z "$FOUND_FILES" ]
 then
-	printf "ERROR: Please provide a directory containing .c, .cpp, .S, .pd or .scd files.\n\n"
-	exit 1
+    printf "ERROR: Please provide a directory containing .c, .cpp, .S, .pd or .scd files.\n\n"
+    exit 1
 fi
 
 [ -z $BBB_PROJECT_NAME ] && BBB_PROJECT_NAME="$(basename $(cd "$PROJECTDIR" && pwd))"
@@ -213,43 +214,43 @@ ssh $BBB_ADDRESS make QUIET=true --no-print-directory -C $BBB_BELA_HOME stop
 check_rsync && RSYNC_AVAILABLE=1 || RSYNC_AVAILABLE=0
 
 uploadBuildRun(){
-	# Copy new source files to the board
-	echo "uploadBuildRun START"
-	printf "Copying new source files to BeagleBone..."
-	if [ "$RSYNC_AVAILABLE" -eq 0 ];
-	then
-		echo "Using scp..."
-		
-		echo "Cleaning the destination folder..."
-		#if rsync is not available, brutally clean the destination folder
-		ssh $BBB_ADDRESS "rm -rf \"$BBB_PROJECT_FOLDER\"; mkdir -p \"$BBB_PROJECT_FOLDER\""
-		echo "Copying the project files"
-		scp -r $PROJECTDIR/* "$BBB_NETWORK_TARGET_FOLDER"
-	else
-		#rsync 
-		# --delete makes sure it removes files that are not in the origin folder
-		# -c evaluates changes using md5 checksum instead of file date, so we don't care about time skews 
-		# --no-t makes sure file timestamps are not preserved, so that the Makefile will not think that targets are up to date when replacing files on the BBB
-		#  with older files from the host. This will solve 99% of the issues with Makefile thinking a target is up to date when it is not.
-		echo "Using rsync..."
-		
-		rsync -ac --out-format="   %n" --no-t --delete-after --exclude=$BBB_PROJECT_NAME --exclude=build --exclude=settings.json $PROJECTDIR"/" "$BBB_NETWORK_TARGET_FOLDER/" #trailing slashes used here make sure rsync does not create another folder inside the target folder
-	fi
+    # Copy new source files to the board
+    echo "uploadBuildRun START"
+    printf "Copying new source files to BeagleBone..."
+    if [ "$RSYNC_AVAILABLE" -eq 0 ];
+    then
+        echo "Using scp..."
+        
+        echo "Cleaning the destination folder..."
+        #if rsync is not available, brutally clean the destination folder
+        ssh $BBB_ADDRESS "rm -rf \"$BBB_PROJECT_FOLDER\"; mkdir -p \"$BBB_PROJECT_FOLDER\""
+        echo "Copying the project files"
+        scp -r $PROJECTDIR/* "$BBB_NETWORK_TARGET_FOLDER"
+    else
+        #rsync 
+        # --delete makes sure it removes files that are not in the origin folder
+        # -c evaluates changes using md5 checksum instead of file date, so we don't care about time skews 
+        # --no-t makes sure file timestamps are not preserved, so that the Makefile will not think that targets are up to date when replacing files on the BBB
+        #  with older files from the host. This will solve 99% of the issues with Makefile thinking a target is up to date when it is not.
+        echo "Using rsync..."
+        
+        rsync -ac --out-format="   %n" --no-t --delete-after --exclude=$BBB_PROJECT_NAME --exclude=build --exclude=settings.json $PROJECTDIR"/" "$BBB_NETWORK_TARGET_FOLDER/" #trailing slashes used here make sure rsync does not create another folder inside the target folder
+    fi
 
-	if [ $? -ne 0 ]
-	then
-		printf "\nError while copying files\n"
-		exit
-	fi
-	
-	# Make new Bela executable and run
-	MAKE_COMMAND="make --no-print-directory QUIET=true -C $BBB_BELA_HOME PROJECT='$BBB_PROJECT_NAME' CL='$COMMAND_ARGS' LDLIBS='$BELA_LDLIBS' CPPFLAGS='$BELA_CPPFLAGS' AT="
-	
-	ssh -t $BBB_ADDRESS "$MAKE_COMMAND run"
+    if [ $? -ne 0 ]
+    then
+        printf "\nError while copying files\n"
+        exit
+    fi
+    
+    # Make new Bela executable and run
+    MAKE_COMMAND="make --no-print-directory QUIET=true -C $BBB_BELA_HOME PROJECT='$BBB_PROJECT_NAME' CL='$COMMAND_ARGS' LDLIBS='$BELA_LDLIBS' CPPFLAGS='$BELA_CPPFLAGS' AT="
+    
+    ssh -t $BBB_ADDRESS "$MAKE_COMMAND run"
 }
 
 echo "Run bela now"
 uploadBuildRun
-	
+    
 fi
 echo "$PROJECTDIR/render.cpp;"
diff --git a/tools/faust2appls/faust2linuxunity b/tools/faust2appls/faust2linuxunity
--- a/tools/faust2appls/faust2linuxunity
+++ b/tools/faust2appls/faust2linuxunity
@@ -33,24 +33,24 @@ do
         usage faust2linuxunity "[options] [Faust options] <file.dsp>"
         platform Linux
         require Jack, Unity
-        echo "Compiles Faust programs to Linux x86_64 library suitable for the Unity environment"
+        echo "Compiles Faust programs to Linux x86_64 libraries suitable for the Unity environment"
         option
         option "-nvoices <num>"
         option "Faust options"
         exit
     fi
 
-	if [ $p = "-nvoices" ]; then
+    if [ $p = "-nvoices" ]; then
         shift
         NVOICES=$1
     elif [ ${p:0:1} = "-" ]; then
-	    OPTIONS="$OPTIONS $p"
-	elif [[ -f "$p" ]] && [ ${p: -4} == ".dsp" ]; then
-	    FILES="$FILES $p"
-	else
-	    OPTIONS="$OPTIONS $p"        
-	fi
-	
+        OPTIONS="$OPTIONS $p"
+    elif [[ -f "$p" ]] && [ ${p: -4} == ".dsp" ]; then
+        FILES="$FILES $p"
+    else
+        OPTIONS="$OPTIONS $p"        
+    fi
+    
 shift
 done
 
@@ -98,11 +98,11 @@ for p in $FILES; do
     (
         cd "$TMP"
         if [ $NVOICES == -1 ]; then
-        	$CXX $CXXFLAGS $LIB -Dmydsp=$NAME -o $LIBNAME $NAME.cpp
-		else
-			$CXX $CXXFLAGS $LIB -Dmydsp=$NAME -DPOLY -o $LIBNAME $NAME.cpp
-		fi
-	) > /dev/null || (echo "$f : C++ to linux library compilation failed in faust2linuxunity"; exit 1)
+            $CXX $CXXFLAGS $LIB -Dmydsp=$NAME -o $LIBNAME $NAME.cpp
+        else
+            $CXX $CXXFLAGS $LIB -Dmydsp=$NAME -DPOLY -o $LIBNAME $NAME.cpp
+        fi
+    ) > /dev/null || (echo "$f : C++ to linux library compilation failed in faust2linuxunity"; exit 1)
 
     # moves binary to final dir
     rm -rf "$SRCDIR/$LIBNAME"
diff --git a/tools/faust2appls/faust2osxiosunity b/tools/faust2appls/faust2osxiosunity
--- a/tools/faust2appls/faust2osxiosunity
+++ b/tools/faust2appls/faust2osxiosunity
@@ -49,62 +49,62 @@ cat > "$2" << DELIM
 <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
 <plist version="1.0">
 <dict>
-	<key>BuildMachineOSBuild</key>
-	<string>16D32</string>
-	<key>CFBundleDevelopmentRegion</key>
-	<string>English</string>
-	<key>CFBundleExecutable</key>
-	<string>$1</string>
-	<key>CFBundleIdentifier</key>
-	<string>com.yourcompany.$1</string>
-	<key>CFBundleInfoDictionaryVersion</key>
-	<string>6.0</string>
-	<key>CFBundleName</key>
-	<string>$1</string>
-	<key>CFBundlePackageType</key>
-	<string>BNDL</string>
-	<key>CFBundleShortVersionString</key>
-	<string>1.0</string>
-	<key>CFBundleSignature</key>
-	<string>????</string>
-	<key>CFBundleSupportedPlatforms</key>
-	<array>
-		<string>MacOSX</string>
-	</array>
-	<key>CFBundleVersion</key>
-	<string>1</string>
-	<key>CFPlugInDynamicRegisterFunction</key>
-	<string></string>
-	<key>CFPlugInDynamicRegistration</key>
-	<string>NO</string>
-	<key>CFPlugInFactories</key>
-	<dict>
-		<key>00000000-0000-0000-0000-000000000000</key>
-		<string>MyFactoryFunction</string>
-	</dict>
-	<key>CFPlugInTypes</key>
-	<dict>
-		<key>00000000-0000-0000-0000-000000000000</key>
-		<array>
-			<string>00000000-0000-0000-0000-000000000000</string>
-		</array>
-	</dict>
-	<key>CFPlugInUnloadFunction</key>
-	<string></string>
-	<key>DTCompiler</key>
-	<string>com.apple.compilers.llvm.clang.1_0</string>
-	<key>DTPlatformBuild</key>
-	<string>8C1002</string>
-	<key>DTPlatformVersion</key>
-	<string>GM</string>
-	<key>DTSDKBuild</key>
-	<string>16C58</string>
-	<key>DTSDKName</key>
-	<string>macosx10.12</string>
-	<key>DTXcode</key>
-	<string>0821</string>
-	<key>DTXcodeBuild</key>
-	<string>8C1002</string>
+    <key>BuildMachineOSBuild</key>
+    <string>16D32</string>
+    <key>CFBundleDevelopmentRegion</key>
+    <string>English</string>
+    <key>CFBundleExecutable</key>
+    <string>$1</string>
+    <key>CFBundleIdentifier</key>
+    <string>com.yourcompany.$1</string>
+    <key>CFBundleInfoDictionaryVersion</key>
+    <string>6.0</string>
+    <key>CFBundleName</key>
+    <string>$1</string>
+    <key>CFBundlePackageType</key>
+    <string>BNDL</string>
+    <key>CFBundleShortVersionString</key>
+    <string>1.0</string>
+    <key>CFBundleSignature</key>
+    <string>????</string>
+    <key>CFBundleSupportedPlatforms</key>
+    <array>
+        <string>MacOSX</string>
+    </array>
+    <key>CFBundleVersion</key>
+    <string>1</string>
+    <key>CFPlugInDynamicRegisterFunction</key>
+    <string></string>
+    <key>CFPlugInDynamicRegistration</key>
+    <string>NO</string>
+    <key>CFPlugInFactories</key>
+    <dict>
+        <key>00000000-0000-0000-0000-000000000000</key>
+        <string>MyFactoryFunction</string>
+    </dict>
+    <key>CFPlugInTypes</key>
+    <dict>
+        <key>00000000-0000-0000-0000-000000000000</key>
+        <array>
+            <string>00000000-0000-0000-0000-000000000000</string>
+        </array>
+    </dict>
+    <key>CFPlugInUnloadFunction</key>
+    <string></string>
+    <key>DTCompiler</key>
+    <string>com.apple.compilers.llvm.clang.1_0</string>
+    <key>DTPlatformBuild</key>
+    <string>8C1002</string>
+    <key>DTPlatformVersion</key>
+    <string>GM</string>
+    <key>DTSDKBuild</key>
+    <string>16C58</string>
+    <key>DTSDKName</key>
+    <string>macosx10.12</string>
+    <key>DTXcode</key>
+    <string>0821</string>
+    <key>DTXcodeBuild</key>
+    <string>8C1002</string>
 </dict>
 </plist>
 DELIM
@@ -130,7 +130,7 @@ do
         option -ios "      create an iOS static library"
         option -universal "generate a 64/32 bits external"
         option "Faust options"
-		# echo "Use 'faust2unity -osx -ios' to also create the c# and JSON files"
+        # echo "Use 'faust2unity -osx -ios' to also create the c# and JSON files"
         echo "See architecture/unity/README.md for more info."
         exit
     fi
@@ -142,9 +142,9 @@ do
         shift
         NVOICES=$1
     elif [ $p = "-source" ]; then
-    	SOURCE=1
+        SOURCE=1
     elif [ $p = "-universal" ]; then
-    	ARCH="-arch i386 -arch x86_64"
+        ARCH="-arch i386 -arch x86_64"
     elif [ ${p:0:1} = "-" ]; then
         OPTIONS="$OPTIONS $p"
     elif [[ -f "$p" ]] && [ ${p: -4} == ".dsp" ]; then
@@ -212,9 +212,9 @@ for p in $FILES; do
         faust -uim -i -a $FAUSTARCH/unity/unityplugin.cpp "$SRCDIR/$NAME.dsp" -o "$MOS/$NAME.cpp" || (echo "$FNAME : Faust to C++ compilation failed in faust2osxiosunity"; exit 1)
         
         if [ $NVOICES == -1 ]; then
-        	 $CXX $CXXFLAGS $ARCH $LDFLAGS -DAPPLE -DPLUGINNAME="$NAME" "$MOS/$NAME.cpp" -o "$MOS/lib$FNAME" || (echo "$FNAME : C++ to OSX library compilation failed in faust2osxiosunity"; exit 1)
+             $CXX $CXXFLAGS $ARCH $LDFLAGS -DAPPLE -DPLUGINNAME="$NAME" "$MOS/$NAME.cpp" -o "$MOS/lib$FNAME" || (echo "$FNAME : C++ to OSX library compilation failed in faust2osxiosunity"; exit 1)
         else
-        	 $CXX $CXXFLAGS $ARCH $LDFLAGS -DPOLY -DAPPLE -DPLUGINNAME="$NAME" "$MOS/$NAME.cpp" -o "$MOS/lib$FNAME" || (echo "$FNAME : C++ to OSX library compilation failed in faust2osxiosunity"; exit 1)
+             $CXX $CXXFLAGS $ARCH $LDFLAGS -DPOLY -DAPPLE -DPLUGINNAME="$NAME" "$MOS/$NAME.cpp" -o "$MOS/lib$FNAME" || (echo "$FNAME : C++ to OSX library compilation failed in faust2osxiosunity"; exit 1)
         fi
        
         rm "$MOS/$NAME.cpp"
diff --git a/tools/faust2appls/faust2w32max6 b/tools/faust2appls/faust2w32max6
--- a/tools/faust2appls/faust2w32max6
+++ b/tools/faust2appls/faust2w32max6
@@ -30,8 +30,8 @@ MAXSDK=/usr/local/include/c74support
 EXT="~.mxe"
 
 if [ ! -d "${MAXSDK}" ]; then
- 	echo "Unable to locate Max/Msp SDK: MAXSDK=${MAXSDK}" 1>&2
- 	exit 1
+     echo "Unable to locate Max/Msp SDK: MAXSDK=${MAXSDK}" 1>&2
+     exit 1
 fi
 
 #------------------------------------------------------------------------------
@@ -69,14 +69,14 @@ for p in $@; do
     fi
 
     if [ "$p" = -icc ]; then
-    	ignore=" "
+        ignore=" "
     elif [ ${p:0:1} = "-" ]; then
-	    OPTIONS="$OPTIONS $p"
-	elif [[ -f "$p" ]] && [ ${p: -4} == ".dsp" ]; then
-	    FILES="$FILES $p"
-	else
-	    OPTIONS="$OPTIONS $p"
-	fi
+        OPTIONS="$OPTIONS $p"
+    elif [[ -f "$p" ]] && [ ${p: -4} == ".dsp" ]; then
+        FILES="$FILES $p"
+    else
+        OPTIONS="$OPTIONS $p"
+    fi
 done
 
 BINARIES=""
@@ -86,32 +86,32 @@ for p in $FILES; do
 
     CUR=$(pwd)
     f=$(basename "$p")
-	SRCDIR=$(dirname "$p")
+    SRCDIR=$(dirname "$p")
 
     # creates a temporary dir
     TDR=$(mktemp -d faust.XXX)
-	TMP="$TDR/${f%.dsp}"
+    TMP="$TDR/${f%.dsp}"
     mkdir "$TMP"
 
     # compile faust to c++
-	faust -i -double -cn ${f%.dsp} -uim -a $FAUSTARCH/max-msp/max-msp64.cpp $OPTIONS "$SRCDIR/$f" -o "$TMP/${f%.dsp}.cpp" || exit
+    faust -i -double -cn ${f%.dsp} -uim -a $FAUSTARCH/max-msp/max-msp64.cpp $OPTIONS "$SRCDIR/$f" -o "$TMP/${f%.dsp}.cpp" || exit
 
     # compile c++ to binary
     (
-		cd "$TMP"
-		echo "TMP=$TMP"
+        cd "$TMP"
+        echo "TMP=$TMP"
 
-		# we need to create the .def file needed to generate the .dll
-		echo "LIBRARY     ${f%.dsp}~" 						 > ${f%.dsp}.def
-		echo "DESCRIPTION 'Faust generated MAX plugin'" 	>> ${f%.dsp}.def
-		echo "EXPORTS     main" 							>> ${f%.dsp}.def
+        # we need to create the .def file needed to generate the .dll
+        echo "LIBRARY     ${f%.dsp}~"                          > ${f%.dsp}.def
+        echo "DESCRIPTION 'Faust generated MAX plugin'"     >> ${f%.dsp}.def
+        echo "EXPORTS     main"                             >> ${f%.dsp}.def
 
-		$CXX $CXXINCS $CXXFLAGS -c "${f%.dsp}.cpp" -o "${f%.dsp}.o"
-		$DLLWRAP --driver-name $CXX --def ${f%.dsp}.def *.o  $LIBS -static -o "${f%.dsp}$EXT"
-		$STRIP "${f%.dsp}$EXT"
+        $CXX $CXXINCS $CXXFLAGS -c "${f%.dsp}.cpp" -o "${f%.dsp}.o"
+        $DLLWRAP --driver-name $CXX --def ${f%.dsp}.def *.o  $LIBS -static -o "${f%.dsp}$EXT"
+        $STRIP "${f%.dsp}$EXT"
     ) > /dev/null || exit
 
-	cp "$TMP/${f%.dsp}$EXT" "$SRCDIR"
+    cp "$TMP/${f%.dsp}$EXT" "$SRCDIR"
 
     # remove temporary directory
     rm -rf "$TDR"
@@ -138,7 +138,5 @@ for p in $FILES; do
     fi
 
 done
-
-
 
 echo "$BINARIES"
diff --git a/tools/faust2appls/faust2w32vst b/tools/faust2appls/faust2w32vst
--- a/tools/faust2appls/faust2w32vst
+++ b/tools/faust2appls/faust2w32vst
@@ -14,8 +14,8 @@
 VST=/usr/local/include/vstsdk2.4
 . faustpath
 if [ ! -d "${VST}" ]; then
-  	echo "unable to locate VST SDK: VST=${VST}" 1>&2
-  	exit 1
+      echo "unable to locate VST SDK: VST=${VST}" 1>&2
+      exit 1
 fi
 
 # these cpp files have to be compiled too
@@ -56,14 +56,14 @@ for p in $@; do
     fi
 
     if [ "$p" = -icc ]; then
-    	ignore=" "
+        ignore=" "
     elif [ ${p:0:1} = "-" ]; then
-	    OPTIONS="$OPTIONS $p"
-	elif [[ -f "$p" ]] && [ ${p: -4} == ".dsp" ]; then
-	    FILES="$FILES $p"
-	else
-	    OPTIONS="$OPTIONS $p"
-	fi
+        OPTIONS="$OPTIONS $p"
+    elif [[ -f "$p" ]] && [ ${p: -4} == ".dsp" ]; then
+        FILES="$FILES $p"
+    else
+        OPTIONS="$OPTIONS $p"
+    fi
 done
 
 BINARIES=""
@@ -73,35 +73,35 @@ for p in $FILES; do
 
     CUR=$(pwd)
     f=$(basename "$p")
-	SRCDIR=$(dirname "$p")
+    SRCDIR=$(dirname "$p")
 
     # creates a temporary dir
     TDR=$(mktemp -d faust.XXX)
-	TMP="$TDR/${f%.dsp}"
+    TMP="$TDR/${f%.dsp}"
     mkdir "$TMP"
 
     # compile faust to c++
-	faust -i -a vst.cpp $OPTIONS "$SRCDIR/$f" -o "$TMP/${f%.dsp}.cpp" || exit
+    faust -i -a vst.cpp $OPTIONS "$SRCDIR/$f" -o "$TMP/${f%.dsp}.cpp" || exit
 
     # compile c++ to binary
     (
-		cd "$TMP"
+        cd "$TMP"
 
-		# we need to create the .def file needed to generate the .dll
-		echo "LIBRARY     ${f%.dsp}" 						 > ${f%.dsp}.def
-		echo "DESCRIPTION 'Faust generated VST plugin'" 	>> ${f%.dsp}.def
-		echo "EXPORTS     VSTPluginMain" 					>> ${f%.dsp}.def
+        # we need to create the .def file needed to generate the .dll
+        echo "LIBRARY     ${f%.dsp}"                          > ${f%.dsp}.def
+        echo "DESCRIPTION 'Faust generated VST plugin'"     >> ${f%.dsp}.def
+        echo "EXPORTS     VSTPluginMain"                     >> ${f%.dsp}.def
 
-		$CXX $CXXINCS $CXXFLAGS -c "$VST/public.sdk/source/vst2.x/audioeffect.cpp" -o audioeffect.o
-		$CXX $CXXINCS $CXXFLAGS -c "$VST/public.sdk/source/vst2.x/audioeffectx.cpp" -o audioeffectx.o
-		$CXX $CXXINCS $CXXFLAGS -c "$VST/public.sdk/source/vst2.x/vstplugmain.cpp" -o vstplugmain.o
-		$CXX $CXXINCS $CXXFLAGS -c "${f%.dsp}.cpp" -o "${f%.dsp}.o"
+        $CXX $CXXINCS $CXXFLAGS -c "$VST/public.sdk/source/vst2.x/audioeffect.cpp" -o audioeffect.o
+        $CXX $CXXINCS $CXXFLAGS -c "$VST/public.sdk/source/vst2.x/audioeffectx.cpp" -o audioeffectx.o
+        $CXX $CXXINCS $CXXFLAGS -c "$VST/public.sdk/source/vst2.x/vstplugmain.cpp" -o vstplugmain.o
+        $CXX $CXXINCS $CXXFLAGS -c "${f%.dsp}.cpp" -o "${f%.dsp}.o"
 
-		$DLLWRAP --driver-name $CXX --def ${f%.dsp}.def *.o  $LIBS -static-libstdc++ -static-libgcc -o "${f%.dsp}$EXT"
-		$STRIP "${f%.dsp}$EXT"
+        $DLLWRAP --driver-name $CXX --def ${f%.dsp}.def *.o  $LIBS -static-libstdc++ -static-libgcc -o "${f%.dsp}$EXT"
+        $STRIP "${f%.dsp}$EXT"
     ) > /dev/null || exit
 
-	cp "$TMP/${f%.dsp}$EXT" "$SRCDIR"
+    cp "$TMP/${f%.dsp}$EXT" "$SRCDIR"
 
     # remove temporary directory
     rm -rf "$TDR"
