Rework SoundUI::addSoundfile, add soundfile handling in faust2msp, faust2max6 and faust2caqt.

diff --git a/tools/faust2appls/faust2caqt b/tools/faust2appls/faust2caqt
--- a/tools/faust2appls/faust2caqt
+++ b/tools/faust2appls/faust2caqt
@@ -27,23 +27,26 @@ POLY="POLY"
 DEPLOY=""
 EFFECT=""
 NVOICES=-1
-SOUNDFILE=""
+SOUNDFILE="0"
+SOUNDFILEDEFS=""
+SOUNDFILEFLAGS=""
 
 while [ $1 ] 
 do
     p=$1
 
     if [ $p = "-help" ] || [ $p = "-h" ]; then
-        echo "faust2caqt [-httpd] [-qrcode] [-soundfile <path>] [-nvoices <num>] [-effect auto|<effect.dsp>] [-midi] [-osc] [-debug] <file.dsp>"
+        echo "faust2caqt [-httpd] [-qrcode] -soundfile [-nvoices <num>] [-effect auto|<effect.dsp>] [-midi] [-osc] [-debug] [-deploy] <file.dsp>"
         echo "Use '-httpd' to activate HTTP control"
         echo "Use '-qrcode' to activate QR code generation"
         echo "Use '-nvoices <num>' to produce a polyphonic self-contained DSP with <num> voices, ready to be used with MIDI or OSC"
-        echo "Use '-soundfile <path>' to activate soundfile Player connected to DSP"
+        echo "Use '-soundfile' when compiling DSP using 'soundfile' primitive, to add needed resources"
         echo "Use '-effect <effect.dsp>' to produce a polyphonic DSP connected to a global output effect, ready to be used with MIDI or OSC"
         echo "Use '-effect auto' to produce a polyphonic DSP connected to a global output effect defined as 'effect' in <file.dsp>, ready to be used with MIDI or OSC"
         echo "Use '-midi' to activate MIDI control"
         echo "Use '-osc' to activate OSC control"
         echo "Use '-debug' to print all the build steps"
+        echo "Use '-deploy' to create a self-contained application using 'macdeployqt'"
         exit
     fi
 
@@ -59,12 +62,6 @@ do
         if [ $NVOICES -ge 0 ]; then
             CXXFLAGS="$CXXFLAGS -DNVOICES=$NVOICES"
         fi
-    elif [ $p = "-soundfile" ]; then
-        shift
-        SOUNDFILE=$1
-        if [ $SOUNDFILE != "" ]; then
-            CXXFLAGS="$CXXFLAGS -DSOUND_FILE=$SOUNDFILE"
-        fi
     elif [ $p = "-effect" ]; then
         POLYDEFS="DEFINES += POLY2"
         POLY="POLY2"
@@ -72,6 +69,10 @@ do
         EFFECT=$1
     elif [ $p = "-midi" ]; then
         MIDIDEFS="DEFINES += MIDICTRL"
+    elif [ $p = "-soundfile" ]; then
+        SOUNDFILE="1"
+        SOUNDFILEDEFS="DEFINES += SOUNDFILE"
+        SOUNDFILEFLAGS=`pkg-config --cflags --static --libs sndfile`
     elif [ $p = "-osc" ]; then
 		 OSCDEFS="DEFINES += OSCCTRL"
 		 OSCLIBS="-lOSCFaust"
@@ -139,24 +140,51 @@ for p in $FILES; do
 
             process = adaptor(library("$SRCDIR/$f").process, library("$SRCDIR/$f").effect) : library("$SRCDIR/$f").effect;
 EndOfCode
-            faust -i -a $ARCHFILE $OPTIONS "$SRCDIR/$f" -o "$TMP/${f%.dsp}_voice.cpp" || exit
+            faust -i -json -a $ARCHFILE $OPTIONS "$SRCDIR/$f" -o "$TMP/${f%.dsp}_voice.cpp" || exit
             faust -i -cn effect -a minimal-effect.cpp "$TMP/effect.dsp" -o "$TMP/effect.cpp" || exit
             rm "$TMP/effect.dsp"
         else
-            faust -i -a $ARCHFILE $OPTIONS "$SRCDIR/$f" -o "$TMP/${f%.dsp}_voice.cpp" || exit
+            faust -i -json -a $ARCHFILE $OPTIONS "$SRCDIR/$f" -o "$TMP/${f%.dsp}_voice.cpp" || exit
             faust -i -cn effect -a minimal-effect.cpp "$SRCDIR/$EFFECT" -o "$TMP/effect.cpp" || exit
         fi
     else
-        faust -i -a $ARCHFILE $OPTIONS "$SRCDIR/$f" -o "$TMP/${f%.dsp}.cpp" || exit
+        faust -i -json -a $ARCHFILE $OPTIONS "$SRCDIR/$f" -o "$TMP/${f%.dsp}.cpp" || exit
     fi
 
     # compile c++ to binary
     (
 	    cd "$TMP"
-	    qmake -project "QT += widgets printsupport network" "CONFIG+=warn_off" "$CLANGOPT" "INCLUDEPATH+=$CUR" "INCLUDEPATH+=$FAUSTINC /opt/local/include" "QMAKE_CXXFLAGS= $CXXFLAGS -Wno-unused-parameter $FAUSTTOOLSFLAGS" "LIBS+=$ARCHLIB $OSCLIBS $HTTPLIBS" "HEADERS+=$FAUSTINC/faust/gui/faustqt.h" "RESOURCES+= $FAUSTINC/faust/gui/Styles/Grey.qrc" "$OSCDEFS" "$HTTPDEFS" "$QRDEFS" "$POLYDEFS" "$MIDIDEFS" 
+	    qmake -project "QT += widgets printsupport network" "CONFIG+=warn_off" "$CLANGOPT" "INCLUDEPATH+=$CUR" "INCLUDEPATH+=$FAUSTINC /opt/local/include" "QMAKE_CXXFLAGS= $CXXFLAGS -Wno-unused-parameter $FAUSTTOOLSFLAGS" "LIBS+=$ARCHLIB $SOUNDFILEFLAGS $OSCLIBS $HTTPLIBS" "HEADERS+=$FAUSTINC/faust/gui/faustqt.h" "RESOURCES+= $FAUSTINC/faust/gui/Styles/Grey.qrc" "$OSCDEFS" "$HTTPDEFS" "$QRDEFS" "$POLYDEFS" "$MIDIDEFS $SOUNDFILEDEFS"
 	    qmake $SPEC
         make
     ) > /dev/null || exit
+
+
+    if [ "$SOUNDFILE" = "1" ]; then
+        echo $p.json
+        # get all soundfiles from the JSON file
+        cat $p.json | awk '
+            BEGIN { FS=":"; SOFI=0; }
+                /"soundfile"/ { SOFI=1; }
+                /"label"/ {
+                if (SOFI) {
+                    match($2, /"[^"]*/);
+                    print substr($2, RSTART+1, RLENGTH-1);
+                    SOFI=0;
+                }
+            }
+        ' > $p-tmp.txt
+        # copy found soundfiles in the final binary
+        for snd in $(cat $p-tmp.txt); do
+            if [ -f $snd ]; then
+                echo "Copy $snd in ${f%.dsp}$EXT"
+                cp $snd "$TMP/${f%.dsp}$EXT"
+            else
+                echo "Error: file $snd not found !"
+            fi
+        done
+        rm $p-tmp.txt
+    fi
 
     # on Mac add the QT libraries to the bundle
     if [[ $(uname) == Darwin ]]; then
@@ -166,6 +194,8 @@ EndOfCode
     fi
 
     rm -rf "$SRCDIR/${f%.dsp}$EXT"
+    rm $p.json
+
     cp -r "$TMP/${f%.dsp}$EXT" "$SRCDIR/${f%.dsp}$EXT"
     RMTMP=true
     if $DEBUG;
diff --git a/tools/faust2appls/faust2max6 b/tools/faust2appls/faust2max6
--- a/tools/faust2appls/faust2max6
+++ b/tools/faust2appls/faust2max6
@@ -18,6 +18,9 @@ POLY=""
 NOPATCH="0"
 NVOICES=-1
 EFFECT=""
+SOUNDFILE="0"
+SOUNDFILEDEFS=""
+SOUNDFILEFLAGS=""
 
 # path to max SDK
 
@@ -90,11 +93,12 @@ do
     p=$1
 
     if [ $p = "-help" ] || [ $p = "-h" ]; then
-        echo "faust2max6 [-nvoices <num>] [-effect <effect.dsp>] [-midi] [-nopatch] <file.dsp>"
+        echo "faust2max6 [-nvoices <num>] [-effect <effect.dsp>] [-midi] [-nopatch] [-soundfile] <file.dsp>"
         echo "Use '-nvoices <num>' to produce a polyphonic self-contained DSP with <num> voices, ready to be used with MIDI"
         echo "Use '-effect <effect.dsp>' to produce a polyphonic DSP connected to a global output effect, ready to be used with MIDI"
         echo "Use '-midi' to activate MIDI control"
         echo "Use '-nopatch' to deactivate patch generation"
+        echo "Use '-soundfile' when compiling DSP using 'soundfile' primitive, to add needed resources"
         exit
     fi
 
@@ -121,6 +125,10 @@ do
         EFFECT=$1
     elif [ $p = "-midi" ]; then
         MIDIDEFS="-DMIDICTRL"
+    elif [ $p = "-soundfile" ]; then
+        SOUNDFILE="1"
+        SOUNDFILEDEFS="-DSOUNDFILE"
+        SOUNDFILEFLAGS=`pkg-config --cflags --static --libs sndfile`
     elif [ $p = "-nopatch" ]; then
         NOPATCH="1"
     elif [ ${p:0:1} = "-" ]; then
@@ -166,9 +174,9 @@ for p in $FILES; do
 
     # compile faust to c++
     if [ "$EFFECT" = "" ]; then
-        faust -i -double -a $FAUSTLIB/max-msp/max-msp64.cpp $OPTIONS "$SRCDIR/$f" -o "$TMP/${f%.dsp}.cpp" || exit
+        faust -i -double -json -a $FAUSTLIB/max-msp/max-msp64.cpp $OPTIONS "$SRCDIR/$f" -o "$TMP/${f%.dsp}.cpp" || exit
     else
-        faust -i -double -a $FAUSTLIB/max-msp/max-msp64.cpp $OPTIONS "$SRCDIR/$f" -o "$TMP/${f%.dsp}.cpp" || exit
+        faust -i -double -json -a $FAUSTLIB/max-msp/max-msp64.cpp $OPTIONS "$SRCDIR/$f" -o "$TMP/${f%.dsp}.cpp" || exit
         faust -i -double -cn effect -a $FAUSTLIB/minimal-effect.cpp "$SRCDIR/$EFFECT" -o "$TMP/effect.cpp" || exit
     fi
 
@@ -176,9 +184,8 @@ for p in $FILES; do
     (
 	cd "$TMP"
 	install -d "${f%.dsp}$EXT/Contents/MacOS"
-	#$CC $CXXFLAGS -mmacosx-version-min=10.7 -Wfatal-errors -framework Carbon $POLYDEFS $MIDIDEFS -I ../../ -I$MAXINC -I$MSPINC $FAUSTTOOLSFLAGS -F$MAXINC -F$MSPINC -framework MaxAPI -framework MaxAudioAPI `pkg-config --cflags --static --libs sndfile` -arch i386 -arch x86_64 -Wl,-U,_object_method_imp -Wl,-Y,1455 -bundle "${f%.dsp}.cpp" -o "${f%.dsp}$EXT/Contents/MacOS/${f%.dsp}~"
-    $CC $CXXFLAGS -mmacosx-version-min=10.7 -Wfatal-errors -framework Carbon $POLYDEFS $MIDIDEFS -I ../../ -I$MAXINC -I$MSPINC $FAUSTTOOLSFLAGS -F$MAXINC -F$MSPINC -framework MaxAPI -framework MaxAudioAPI -arch i386 -arch x86_64 -Wl,-U,_object_method_imp -Wl,-Y,1455 -bundle "${f%.dsp}.cpp" -o "${f%.dsp}$EXT/Contents/MacOS/${f%.dsp}~"
-    ) > /dev/null || exit
+    $CC $CXXFLAGS -mmacosx-version-min=10.7 -Wfatal-errors -framework Carbon $POLYDEFS $MIDIDEFS $SOUNDFILEDEFS -I ../../ -I$MAXINC -I$MSPINC $FAUSTTOOLSFLAGS -F$MAXINC -F$MSPINC -framework MaxAPI -framework MaxAudioAPI $SOUNDFILEFLAGS -arch i386 -arch x86_64 -Wl,-U,_object_method_imp -Wl,-Y,1455 -bundle "${f%.dsp}.cpp" -o "${f%.dsp}$EXT/Contents/MacOS/${f%.dsp}~"
+   ) > /dev/null || exit
 
     rm -rf "$SRCDIR/${f%.dsp}$EXT"
 
@@ -188,8 +195,34 @@ for p in $FILES; do
     # Create Info.plist
     createInfoPList "${f%.dsp}~" "$TMP/${f%.dsp}$EXT/Contents/Info.plist"
 
+    if [ "$SOUNDFILE" = "1" ]; then
+        # get all soundfiles from the JSON file
+        cat $p.json | awk '
+                        BEGIN { FS=":"; SOFI=0; }
+                            /"soundfile"/ { SOFI=1; }
+                            /"label"/ {
+                            if (SOFI) {
+                                match($2, /"[^"]*/);
+                                print substr($2, RSTART+1, RLENGTH-1);
+                                SOFI=0;
+                            }
+                        }
+        ' > $p-tmp.txt
+        # copy found soundfiles in the final binary
+        for snd in $(cat $p-tmp.txt); do
+            if [ -f $snd ]; then
+                echo "Copy $snd in ${f%.dsp}$EXT"
+                cp $snd "$TMP/${f%.dsp}$EXT"
+            else
+                echo "Error: file $snd not found !"
+            fi
+        done
+        rm $p-tmp.txt
+    fi
+
     cp -r "$TMP/${f%.dsp}$EXT" "$SRCDIR/${f%.dsp}$EXT"
     rm -rf "$TDR"
+    rm $p.json
 
     # collect binary file name for FaustGIDE
     BINARIES="$BINARIES$SRCDIR/${f%.dsp}$EXT;"
