print variable-name in error message (to make it easier to fix)

diff --git a/tools/faust2appls/faust2w32puredata b/tools/faust2appls/faust2w32puredata
--- a/tools/faust2appls/faust2w32puredata
+++ b/tools/faust2appls/faust2w32puredata
@@ -21,7 +21,7 @@ CXX="${MINGWPREFIX}g++"
 (which "$CXX" >/dev/null) || (echo "MingW compiler $CXX not found"; exit 1)
 
 if [ ! -e "${PDW32BINDIR}/pd.dll" ]; then
-  echo "Unable to locate pd.dll in ${PDW32BINDIR}!" 1>&2
+  echo "Unable to locate pd.dll: PDW32BINDIR=${PDW32BINDIR}!" 1>&2
   exit 1
 fi
 
